name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    concurrency: deploy
    permissions:
      pages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest

      - name: Deploy mkdocs
        shell: nix develop --impure --command {0}
        run: |
          mkdocs gh-deploy
